name: CI & Docker Push to GHCR

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Lint with flake8
      - name: Lint with flake8
        run: |
          flake8 src tests

      # Step 5: Check formatting with black
      - name: Check formatting with black
        run: |
          black --check src tests

      # Step 6: Run tests with pytest
      - name: Run tests
        run: |
          pytest

      # Step 7: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/python-template:latest .

      # Step 9: Push Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.actor }}/python-template:latest